base2Services/cfn-guardian

- Dockerfile
- lib/cfnguardian/compile.rb
- lib/cfnguardian/config/defaults.yaml
- lib/cfnguardian/models/alarm.rb
- lib/cfnguardian/models/event_subscription.rb
- lib/cfnguardian/resources/vpn_tunnel.rb
Adding VPN Tunnel monitoring
It seems to build fine:
```
❯ gem build cfn-guardian.gemspec
WARNING:  description and summary are identical
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
Successfully built RubyGem
Name: cfn-guardian
Version: 0.6.7
File: cfn-guardian-0.6.7.gem
❯ gem install cfn-guardian-0.6.7.gem
Successfully installed cfn-guardian-0.6.7
Parsing documentation for cfn-guardian-0.6.7
Done installing documentation for cfn-guardian after 0 seconds
1 gem installed
❯ cfn-guardian compile --config alarms.yaml --region us-east-1
could not extract property type for Parameters from AWSDataBrewRecipeAction, assuming Json
{"Documentation"=>"http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-recipe-action.html#cfn-databrew-re …
```
> Added VPN_Tunnel component

- lib/cfnguardian/config/defaults.yaml
- lib/cfnguardian/models/alarm.rb
Currently since Id is set as the Broker name, adding multiple Queue resources results in only the last one having alarm resources in the final template since the unique resource hash is based on the Id. In this fix I've switched the Id to be the queue name, which seems more appropriate for the resource group and resolves the issue
> Set Queue name as Id for Queue resource to make sure alarms are unique

- lib/cfnguardian/resources/lambda.rb
IteratorAge won't post metrics unless there is an issue, so apart from then it will be in "Insufficient data"
Duration similar story.
Could probably set errors and throttles to notBreaching as well really.
> Change lambda alarms to notBreaching

- lib/cfnguardian/resources/base.rb
Actually the bug of [#39 ](https://github.com/base2Services/cfn-guardian/issues/39) extends to all GroupOverrides properties (not only the alarm_action), this happens when more than one resource is defined in the Resource group. Since the overrides parameter of the [get_alarms function](https://github.com/base2Services/cfn-guardian/blob/3b9349696916ba93cc2d4a2eb7fff9aab1d69dce/lib/cfnguardian/resources/base.rb#L28) is passed by reference when the [GroupOverrides property is deleted ](https://github.com/base2Services/cfn-guardian/blob/3b9349696916ba93cc2d4a2eb7fff9aab1d69dce/lib/cfnguardian/resources/base.rb#L34) for the first time, it's deleted in its reference as well. Using a deep copy of the overrides before making any changes to it prevents this behavior.
> Fixing GroupOverrides bug

- lib/cfnguardian/resources/apigateway.rb
- lib/cfnguardian/resources/lambda.rb
All of these alarms' default behaviour is to not receive data, so they should be in OK state not INSUFFICIENT_DATA state when not in ALARM state.
> Set missing data to notBreaching for APIGW and lambda

- lib/cfnguardian/resources/amazonmq_broker.rb
Fix [#42](https://github.com/base2Services/cfn-guardian/issues/42).
The [wrong name is set](https://github.com/base2Services/cfn-guardian/blob/5633c67a6f7742da780abad0661ace6840b03344/lib/cfnguardian/resources/amazonmq_broker.rb#L16) for the CpuCreditBalanceWarning default alarm.
```yaml
alarm = CfnGuardian::Models::AmazonMQBrokerAlarm.new(@resource)
alarm.name = 'CpuCreditBalanceCritical' # CpuCreditBalanceWarning
alarm.metric_name = 'CpuCreditBalance'
alarm.comparison_operator = 'LessThanThreshold'
alarm.statistic = 'Minimum'
alarm.threshold = 30
alarm.evaluation_periods = 1
alarm.treat_missing_data = 'notBreaching'
alarm.alarm_action = 'Warning'
@alarms.push(alarm)
```
> Fixing duplicated CpuCreditBalanceCritical for lib/cfnguardian/resources/amazonmq_broker.rb

- lib/cfnguardian/resources/log_group.rb
Majority of the time a metric filter will not be receiving data, so it will sit in INSUFFICIENT_DATA until it receives data and goes into ALARM, then back afterwards, there is no possibility for it to go into OK state.
I'm on a quest to make INSUFFICIENT_DATA a thing of the past!
> Set metric filter alarms to treat missing data as not breaching

- lib/cfnguardian/models/alarm.rb
All of the alarms for CloudFront distributions are for error rates, which the majority of the time shouldn't have any data.
> Set CloudFront alarms to treat missing data as notBreaching

- lib/cfnguardian/resources/http.rb
As usual, these metrics usually have no data at all.
> Set SSL alarms to treat missing data as notBreaching

- lib/cfnguardian/resources/amazonmq_broker.rb
This is how frequently Cloudwatch updates the CPU credits metric, and when set to 1 minute, causes issues with the alarm opening/closing (opens because <15, closes because no data for 4 minutes, opens again because <15, etc).
> Updated AMQ CPU Credits to use 5 minute periods

- docs/event_subscriptions.md
Through a lot of trial and error and looking at the code, I found out that the config block for event subscriptions is wrong in the docs. It needs to be `EventSubscriptions` (plural).
Confirmation can be found here: https://github.com/base2Services/cfn-guardian/blob/4c12dc62e7f7f6f1012992bd0022522f66be87c6/lib/cfnguardian/compile.rb#L67
It's also not very clear what the syntax for enabling subscriptions is, so I added a section to instruct what the syntax is. I decided this was necessary since the syntax for disabling is different, which is a bit confusing.
> Fix error and add section for EventSubscriptions

- lib/cfnguardian/resources/ec2_instance.rb
I assume this alarm was a victim of a copy/paste of the CPU Utilisation alert above it. According to official docs:
```
StatusCheckFailed
Reports whether the instance has passed both the instance status check and the system status check in the last minute.
This metric can be either 0 (passed) or 1 (failed).                 
By default, this metric is available at a 1-minute frequency at no charge.
```
> Fix default properties for ec2 status check alarm

- lib/cfnguardian/resources/nrpe.rb
Currently both warning and critical alarms are set to alarm if they receive data greater than 0, this change defines them to make it clearer and so that critical alarms are correct.
> Set the thresholds for NRPE alarms

- lib/cfnguardian/resources/lambda.rb
This alarm is largely unnecessary as the duration only really matters if the function times out, which would set off the errors alarm anyway.
This is to disable it by default so that it is only used if someone has a specific need for it.
> Disable lambda duration by default

- lib/cfnguardian/resources/application_targetgroup.rb
PR to change the defaults of ALB target response time to the metspec suggested values
https://github.com/base2Services/metspec/blob/main/metrics/AWS/ApplicationELB/metrics.json#L985
> alter targetresponsetime to metspec suggestions

- lib/cfnguardian/resources/rds_cluster.rb
For scenarios where successful failovers require attention.
EG: When a cluster has a smaller reader than its writer, and a manual failover back to the larger instance is required.
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_Events.Messages.html#USER_Events.Messages.cluster
> Add optional event subscription for db cluster failover finished events

- lib/cfnguardian/resources/nrpe.rb
Currently, both the warning and critical alarms for NRPE are assigned the critical alarm action. This change is mostly to make it so warnings are actually warnings, but also to make it clear for criticals as well.
> Specify alarm action in NRPE

- lib/cfnguardian/resources/apigateway.rb
Like with lambda function duration and target group target response time, this metric is not useful in most cases.
> Set latency to disabled by default

- lib/cfnguardian/models/check.rb
- lib/cfnguardian/models/event.rb
- Updated defaults in web socket check lambda
```
self.defaults = {
self.ENDPOINT : 'www.google.com',
self.MESSAGE : '{}',
self.EXPECTED_RESPONSE : '{',
self.CW_METRICS_NAMESPACE: 'WebSocketCheck',
self.REPORT_AS_CW_METRICS: '1',
self.TIMEOUT : 30
}
```
- Changed timeout to configurable value via alarms.yaml file
```
Resources:
WebSocket:
- Id: 'www.google.com'
Message: '{}'
Expected_Response: '{'
Timeout: 45
```
- Fixed error output in TimeTaken
```
return {'Available': 0, 'TimeTaken': int((t2 - t0) * 1000)}
```
Changes to aws-lambda-websocket [here](https://github.com/base2Services/aws-lambda-websocket-check/commit/01e4837e8e33099dcce310b0db779f0ed447eef8) and [here](https://github.com/base2Services/aws-lambda-websocket-check/commit/fb374fcf606b921d3745d7171d81ab5a32135d2f)
> Updated web socket check

- lib/cfnguardian/resources/elastic_search.rb
- lib/cfnguardian/resources/lambda.rb
The default in the base lambda alarm is 5 datapoints 5 evaluation periods, which doesn't really make sense for these alarms as far as I'm aware. It makes more sense to have them just be one datapoint.
> Reduce datapoints for three lambda alarms

- lib/cfnguardian/compile.rb
Example config 
```yaml
Resources:
DynamoDBTable:
- Id: table-1
- Id: table-2
- Id: table-3
- Id: table-4
MaintenanceGroups:
DynamoReadUsage:    # doesn't work
Schedules:
Disable: '55 23 * * ? *'
Enable: '20 0 * * ? *'
Debug: true
DynamoDBTable:
DynamoDBReadUsage:
- Id: table-4
```
The issue was that because both the `Name` in the MaintenanceGroup and the resource friendly name were not set it matched on the first entry in the resource group because both values were nil.
the change added was to check if the `Name` in the MaintenanceGroup is not nil so we dont match nil values and match on the resource id.
> check if name is set in the mg so it doesnt match against a nil value in the alarm

- lib/cfnguardian/resources/base.rb
with the following config
```yaml
Resources:
LogGroup:
- Id: log-group
MetricFilters:
- MetricName: 'TimeoutError'
Pattern: 'Connection Timed Out'
- MetricName: 'ErorrLog'
Pattern: 'error'
- Id: log-group-2
MetricFilters:
- MetricName: 'TimeoutError2'
Pattern: 'Connection Timed Out'
- MetricName: 'ErorrLog2'
Pattern: 'error'
Templates:
LogGroup:
TimeoutError:
Threshold: 10
ErorrLog:
Threshold: 10
TimeoutError2:
Threshold: 20
ErorrLog2:
Threshold: 20
```
we are able to successfully override alarm property values defined on the log groups
The default behavior for the template block is if there isn't a default alarm that matches a new alarm is created with the details defined in the template. But as this is not want the loggroup resource group is excluded from this behavior.
> dont create alarms when there is no match for loggroups when overriding values via the template block

- docs/custom_checks/sftp.md
- lib/cfnguardian/models/check.rb
- lib/cfnguardian/models/event.rb
- Add ability to override the default connection timeout for SFTP and InternalSFTP checks
```yaml
Resources:
SFTP:
- Id: sftp.example.com
User: user
ServerKey: public-server-key
PrivateKey: /ssm/path/privatekey
Timeout: 10
```
- ServerKey is now a required property, before it was optional. this is for security improvements.
> update sftp check to include timeout property

- lib/cfnguardian.rb
- lib/cfnguardian/models/event_subscription.rb
- lib/cfnguardian/resources/rds_cluster.rb
- lib/cfnguardian/resources/rds_cluster_instance.rb
- lib/cfnguardian/resources/rds_instance.rb
- lib/cfnguardian/stacks/resources.rb
##Changes 
1. capturing the events via the event id rather than the message
```
"EventID": "RDS-EVENT-0049"
```
example events https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.overview.html#rds-cloudwatch-events.db-instances
Event IDs https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.Messages.html#USER_Events.Messages.instance
2. Resource id matching for RDS events moved from detail to the resources key for a more reliable matching pattern
3. Fix tagging bug
The previous release introduced the ability to validate if a resource exists, this feature was missed on the tag-alarms command causing the command to fail.
> change rds event structure to use EventID instead of message to match events

- lib/cfnguardian/models/alarm.rb
- lib/cfnguardian/version.rb
Added support for lambda aliases which are designated in the format of `LambdaName:Alias`, if a `:` is detected in the resource Id for a lambda resource the alarm will be created targeting the suffix alias, if no `:` is detected the logic remains the same as a normal lambda function alarm. 
1. We start with 2 lambda functions, `NormalFunction` and `FunctionWithAlias` which has two alias `Dev` and `Prod`.
2. We deploy guardian with the following alarms.yaml template:
```yaml
Resources:
Lambda:
- Id: NormalFunction
- Id: FunctionWithAlias:Dev
```
Observe that the resource id for `FunctionWithAlias` targets only the `Dev` alias whilst `NormalFunction` has no alias target as such remains the same as before.
3. Observe the created LambdaErrors alarms in Cloudwatch. Observe that the `Dev` alias …
> Add support for lambda aliases

- lib/cfnguardian/tagger.rb
- lib/cfnguardian/version.rb
Added fix for when there are multiple alarm actions associated with a single alarm causing tagging to fail. Tagging now checks if there are multiple severities and if so concatenates into single string joined with '/'.
```
/usr/local/bundle/gems/aws-sdk-core-3.147.0/lib/aws-sdk-core/param_validator.rb:35:in `validate!': expected params[:tags][9][:value] to be a String, got value ["Critical", "EcsCycle"] (class: Array) instead. (ArgumentError)
```
1. Deploy alarm with multiple actions
2. Tag alarms via CLI
3. Observe the tags on the alarm now create successfully.
> Fix tagging for multiple alarm actions

- lib/cfnguardian/resources/nrpe.rb
Fixed issue where trying to compile when inheriting the Nrpe resource would cause a compilation error. 
Issue was there was no override group in the constructor for Nrpe causing it fail due to too many args in the constructor when inheriting.
```yaml
cfn-guardian-0.11.7/lib/cfnguardian/resources/nrpe.rb:7:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
```
```yaml
cfn-guardian compile --config=config.yaml --region ap-southeast-2 --debug
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
DEBUG: Inherited resource group Nrpe for group NrpeNew
DEBUG: overriding CheckDiskCritical alarm properties for resource 1.234.56.7 in resource group …
```
> Nrpe inherit fix

- docs/alarm_templates.md
- lib/cfnguardian/display_formatter.rb
- lib/cfnguardian/models/alarm.rb
- lib/cfnguardian/stacks/resources.rb
- lib/cfnguardian/version.rb
It was requested to remove the OK action to reduce noise, so this allows it to be configurable but enabled by default.
> Add the option to disable the OK action
